# .gitlab-ci.yml
before_script:
  - git config user.email "trikijonas@gmail.com"
  - git config user.name "Jonas Triki"

push_to_heroku:
  variables:
    # I need to control which Git branch I'm on in order to push to Heroku
    publication_branch_name: "master"

  script:
    - git checkout -b $publication_branch_name
    - git commit --allow-empty -m "Publish to Heroku at $(date)"
    - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/team-nasa.git $publication_branch_name:master