# .gitlab-ci.yml
before_script:
  - git config user.email "trikijonas@gmail.com"
  - git config user.name "Jonas Triki"

script:
  - git checkout -b master
  - git commit --allow-empty -m "Publish to Heroku at $(date)"
  - echo $HEROKU_API_KEY
  - git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/team-nasa.git master